# check available option strings at https://github.com/macmpi/xg_multi

# option with -D for device MAC address in hex form
DEV_MAC=""

# option with -H for host MAC address in hex form
HOST_MAC=""

# option with -V for path for device or LUN file
VOLUME=""

# option with -w for polling interval in seconds
WAIT=""

# Full list of options at once (takes precedence)
XG_MULTI_OPTS=""
